### ISSUE TITLE
Add definition for drug role of probe substrate 

### ISSUE THREAD

**Issue by ningyifan** [DIDEO/DIDEO#11]
when general evidence type is "phenotype clinical study", one drug and enzyme are involving in DDI that the drug entity is playing the role of probe substrate. 

We have drug role of precipitant and object in ontology already. The "probe substrate" is another role.

**Comment by mbrochhausen** [comment]
Done:
https://github.com/DIDEO/DIDEO/commit/f7e50b259a2fa630607bd230ecccba60a8ff4134
