### ISSUE TITLE
Request to update DIDEO on NCBO Bioportal by 11/22/17

### ISSUE THREAD

**Issue by rkboyce** [DIDEO/DIDEO#15]
Hello Mathias,
Thank you very much for creating an NCBO Bioportal entry for DIDEO and uploading the October version! This ticket is a request to update that entry with the latest release as of 11/22 in time for the NaPDI external advisory board meeting. Also, here is some information to add to the ontology entry page on http://bioportal.bioontology.org/ontologies/DIDEO

- PUBLICATIONS PAGE : https://dikb.org 
- Documentation page : https://forums.dikb.org/c/ontology-and-representation 

Thanks!
-Rich

**Comment by mbrochhausen** [comment]
New release submitted and metadata added.
