### ISSUE TITLE
DIDEO using some wrong PURLs

### ISSUE THREAD

**Issue by matentzn** [DIDEO/DIDEO#16]
- [ ] http://purl.org/obo/owl/GO#GO_0009987
- [ ] http://purl.org/obo/owl/GO#GO_0001659
- [ ] http://purl.org/obo/owl/GO#GO_0002027
- [ ] http://purl.org/obo/owl/GO#GO_0003674
- [ ] http://purl.org/obo/owl/GO#GO_0003824
- [ ] http://purl.org/obo/owl/GO#GO_0008015
- [ ] http://purl.org/obo/owl/GO#GO_0008217
- [ ] http://purl.org/obo/owl/GO#GO_0009987
- [ ] http://purl.org/obo/owl/GO#GO_0017144
- [ ] http://purl.org/obo/owl/GO#GO_0065008

**Comment by matentzn** [comment]
To maximise OBO interoperability, it would be good to change these to their normal OBO form:

http://purl.obolibrary.org/obo/GO_0008015

**Comment by mbrochhausen** [comment]
oops, thanks for bringing that up. I am fixing this asap.

**Comment by YojanaGadiya** [comment]
@mbrochhausen is the issue fixed?

**Comment by mbrochhausen** [comment]
Thanks for the reminder. Not yet. I am fixing that today.

**Comment by mbrochhausen** [comment]
Fixed!
https://github.com/DIDEO/DIDEO/commit/de7f03573d20fb427546c02df59b2fbafff0b134
