### ISSUE TITLE
Confusing ontology labels

### ISSUE THREAD

**Issue by psiotwo** [DIDEO/DIDEO#19]
The ontology metadata contain two label statements. The second might be better represented as a dc:description for example. Also there is an extra trailing space there.

<rdfs:label xml:lang="en">DIDEO</rdfs:label>
<rdfs:label xml:lang="en">Drug-drug Interaction and Drug-drug Interaction Evidence Ontology </rdfs:label>

**Comment by mbrochhausen** [comment]
Hi Petr, thanks for pointing this out. I think the first one is not supposed to be a label, but a iao:alternative term. I'll make the edit and publish a new version of the ontology asap, then close this issue.

**Comment by mbrochhausen** [comment]
Fixed by commit https://github.com/DIDEO/DIDEO/commit/8565ed1f73fc1764ccf2dd6f5812f0e16371a8bb
