### ISSUE TITLE
Revisit definition of 'material entity participating in drug-drug interaction'

### ISSUE THREAD

**Issue by mbrochhausen** [DIDEO/DIDEO#9]
Currently, this is not an Aristotelian definition. It is not clear that an Aristotelian definition can be achieved here. The definition reads:
"A drug product or drug ingredient that participates in a drug-drug interaction."

**Comment by grosscol** [comment]
Does this require a definition?  Could the entities be delegated to whichever ontology defines them and simply state that the DDI `has_participant` using CheBI or GO entities as the object?

e.g.  
Some DDI `has_participant` some CheBI compound 
Some DDI `has_participant` some GO class of macromolecules

**Comment by mbrochhausen** [comment]
In developing ontologies providing a textual definition is regarded important. Never trust words to do all the work for you. Think about the word "cell" and the multitude of meanings it can take inside and outside of biology.

**Comment by grosscol** [comment]
The word "vector" is also a particularly vexing term.  I was wondering if you could completely eliminate the class `material entity participating in drug-drug interaction` by adding `has_participant` `Material Entity` to the definition of `Drug Drug Interaction`.

In that way, any system using this ontology could specify any relevant material entity (cell, vector, ect..) that is a participant in a putative drug-drug interaction.

**Comment by mbrochhausen** [comment]
Ok, I understand the proposal now. Thanks. I agree that that could be done. However, for our application we need to explicitly represent that class. 

I added the axiom you propose to Drug Drug Interaction to the development file and fixed the textual definition.
 
Closed this item with the following 2 commits:
https://github.com/DIDEO/DIDEO/commit/cb0fba719d7cadc2d6c5946e371bbd146c945891
https://github.com/DIDEO/DIDEO/commit/3efe5eb4df39eb4d921a7b2f20c4f6767f05b996
